### ISSUE TITLE
Some proposals to enhance

### ISSUE THREAD

**Issue by goodwinpress** [davidsneighbour/colossus-wp-options-framework#106]
Hi! I have worked a lot with TF as theme developer and there are 4 key issues in TF that always frustrate me. Can it be added or fixed in Colossus?

1) Add options import / export
Ability to copy and paste theme / plugin settings from options page from one site to another. Аs well as in [OptionTree](https://github.com/valendesigns/option-tree/tree/master/includes).
For example https://prnt.sc/u4y4t4

2) Add theme demo importer
Ability to import theme live demo content and theme options.

3) Transfer issue
When user transfer site from one domain to another (all files and database, manually or using Duplicator), all settings in options page are vanishing. 

4) Issue with multilingual plugins
Lack of ability to translate strings from editor and text fields using plugins like Polylang etc.

**Comment by davidsneighbour** [comment]
If you would break this into four separate issues I would gladly add my detailed opinions to them. All four are good. 3 must be a bug and might be solved/mitigated by 1. 2 is in some rudimentary form implemented for the testing suite and I think we can move it into the core of the framework and 4 is my pet peeve. I would like to make all strings translatable by at latest 2.2, maybe even 2.1, even those that are created by scripts implementing the framework.

**Comment by goodwinpress** [comment]
Thank you!
What should I do? Create a new separate item for each question?

**Comment by davidsneighbour** [comment]
Yes, that would be the best. Each issue in it's own Github issue, so we can work on single items :)

**Comment by davidsneighbour** [comment]
see #107 #108 #109 #110
