### ISSUE TITLE
Enable multisite compatibility

### ISSUE THREAD

**Issue by codeclinic** [davidsneighbour/colossus-wp-options-framework#38]
First, Thanks for this great framework.
Currently I am using your framework with my plugin with embedding option. It would be a great feature if you add multi site compatibility as I am doing this by editing your framework core files. As you framework increasing popularity among developers I am facing conflicts with other plugin or theme developers who use the same framework.
Currently I edited the code in class-titan-framework

```

$multisite = true; // in my plugin file

 if ( $multisite ) {
                update_site_option( $this->optionNamespace . '_options', serialize( $this->allOptions[$this->optionNamespace] ) );
            } else {
                update_option( $this->optionNamespace . '_options', serialize( $this->allOptions[$this->optionNamespace] ) );
            }
```

same like for getting options

```
 if ( $multisite ) {
            $currentOptions = get_site_option( $this->optionNamespace . '_options' );
        } else {
            $currentOptions = get_option( $this->optionNamespace . '_options' );
        }
```

It's working great with my edit. How about adding this to your framework?

Ref: https://github.com/gambitph/Titan-Framework/issues/305

**Comment by codeclinic** [comment]
hm, it seems back in 2014 titan framework had support for multisite, but was removed for some reason.

https://www.diffchecker.com/ynbmxm89

**Comment by davidsneighbour** [comment]
Testing (once it's working) is done with and without multisite, so it seems to be integrated in some form. I'll add these fixes and from there we see what else is missing.

The subissue (problems with plugins using the framework too) should be put into it's own issue. As far as I remember the way to work around this is to check if the class already exists before requiring the file. This check should be done by the framework itself and result in a readable message (maybe with info about used versions, which one is more up to date, contact the developer to optimize usage of the framework).

**Comment by davidsneighbour** [comment]
note: no need for setting a parameter, we will use `is_multisite()` to detect WP Multisite. 
see: https://developer.wordpress.org/reference/functions/is_multisite/

please see branch `hotfix/issue38` for a start (when I upload it).

I am not sure (@codeclinic) if this is really a feature we want. get_site_option and set_site_option seem to work on ALL sites in a network. That might not be the way it is expected to work. Single sites should be able to set options on their own? 

We need to differentiate between "setting for all sites" and "setting for a single site" here. The way these functions work it's applied globally. I don't know if that is the expected result? What user case do we have for an option that is applied to all sub-sites in a multisite setting?

**Comment by codeclinic** [comment]
Honestly, I'm not sure that multisite is a good idea. From my perspective Colossus is for adding to themes and plugins and is therefore more single site centric. Having to differential controls between local and multisite would just make things overly complicated.

**Comment by davidsneighbour** [comment]
I see no way to control from a network administrators point of view how local settings are set. It might make sense if a network admin wants certain settings to be identical over all sites, but I am not sure _where exactly_ this option would need to be set. The way I see the plugin now is per single site, not in a global sense...

Let's put this into a later point of discussion :)

**Comment by codeclinic** [comment]
Personally I say, lets rule this out for now at least. If there is a demand for it people can open and an issue and we can go from there. We need to focus elsewhere until their is a compelling reasoning for multisite. At present, there just isnt one.
