### ISSUE TITLE
PHP 7.4 issue

### ISSUE THREAD

**Issue by codeclinic** [davidsneighbour/colossus-wp-options-framework#4]
There is an issue with TF at php 7.4

Trying to access array offset on value of type null in... titan-framework/lib/class-admin-page.php on line 78

So it's

$settings['parent'] = $this->settings['id'];

at function

public function createAdminPanel( $settings ) { $settings['parent'] = $this->settings['id']; return $this->owner->createAdminPanel( $settings ); }

See: https://github.com/gambitph/Titan-Framework/issues/427

**Comment by goodwinpress** [comment]
I've got the solution, by the way. Hired a contractor to fix it. File lib/class-admin-page.php

line 19, change

`	public $settings;`

to

`public $settings = array();`

and then change at lines 77 and 83

`	$settings['parent'] = $this->settings['id'];`

and

`	$settings['parent'] = $this->settings['id'];`

to

` $settings['parent'] = $this->settings['id'] ?? null;`

**Comment by codeclinic** [comment]
@goodwinpress If you could create pull request for this it would be a great help. Thanks.

**Comment by davidsneighbour** [comment]
Those line numbers aren't right, but I added a PR for this. Have a look and let me know if this fixes the issue.

**Comment by goodwinpress** [comment]
Yes, all correct.

**Comment by davidsneighbour** [comment]
fixed in #dc8fbcc

**Comment by davidsneighbour** [comment]
@all-contributors 

add @davidsneighbour for bug,code,content,data,doc,design,ideas,infra,maintenance,projectManagement,question,review,security,test
add @codeclinic for bug,ideas,question
add @goodwinpress for bug,code

**Comment by davidsneighbour** [comment]
bear with me ;)

@all-contributors add @davidsneighbour for bug,code,content,data,doc,design,ideas,infra,maintenance,projectManagement,question,review,security,test
@all-contributors add @codeclinic for bug,ideas,question
@all-contributors add @goodwinpress for bug,code

**Comment by davidsneighbour** [comment]
@all-contributors please add @davidsneighbour for bug, code, content, data, doc, design, ideas, infra, maintenance, projectManagement, question, review, security and test

@all-contributors please add @codeclinic for bug, ideas and question

@all-contributors please add @goodwinpress for bug and code

**Comment by davidsneighbour** [comment]
@all-contributors please add @davidsneighbour for bug, code, content, data, doc, design, ideas, infra, maintenance, projectManagement, question, review, security and test

**Comment by davidsneighbour** [comment]
@all-contributors please add @codeclinic for bug, ideas and question

**Comment by davidsneighbour** [comment]
@all-contributors please add @goodwinpress for bug and code
