### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by codeclinic** [davidsneighbour/colossus-wp-options-framework#49]
Titan was translated using Transifex which appears to require a monthly subscription of at least $139pcm. We always translate our plugins using locally using Poedit.

Any suggestions on how we should make it as easy as possible for people to translate Colossus? Transifex seems out of the question unless I'm missing some OS option. Do you know of any alternatives?

As we make changes to Colossus we're going to be creating new strings and probably changing existing ones and so this will need further translation. 

Failing any better suggestions after each significant update I create a .Po file and we link to it via the readme. Translators can then download it, make their .mo file and submit the translation via a PR or email.

**Comment by codeclinic** [comment]
Ok, I see you have translations going on already: https://www.transifex.com/davids-neighbour/colossus-wp-options-framework/

**Comment by davidsneighbour** [comment]
Open Source gets a package for free :) I am not sure yet if we will receive one, that decision will be based on their judgement. but I went ahead and checked it out. I would prefer some kind of a hosted solution so everybody can help.
